/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedNotificationsIndexImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedMessagesIndexImport } from './routes/_authenticated/messages/index'
import { Route as AuthenticatedHomeIndexImport } from './routes/_authenticated/home/index'
import { Route as AuthenticatedFriendsIndexImport } from './routes/_authenticated/friends/index'
import { Route as AuthenticatedUsernameIndexImport } from './routes/_authenticated/$username/index'
import { Route as authVerifyEmailIndexImport } from './routes/(auth)/verify-email/index'
import { Route as authResetIndexImport } from './routes/(auth)/reset/index'
import { Route as authRegisterIndexImport } from './routes/(auth)/register/index'
import { Route as authNewPasswordIndexImport } from './routes/(auth)/new-password/index'
import { Route as AuthenticatedMessagesLayoutImport } from './routes/_authenticated/messages/_layout'
import { Route as AuthenticatedFriendsLayoutImport } from './routes/_authenticated/friends/_layout'
import { Route as AuthenticatedUsernameLayoutImport } from './routes/_authenticated/$username/_layout'
import { Route as AuthenticatedPostsPostIdIndexImport } from './routes/_authenticated/posts/$postId/index'
import { Route as AuthenticatedUsernameEditIndexImport } from './routes/_authenticated/$username/edit/index'
import { Route as AuthenticatedUsernameAddIndexImport } from './routes/_authenticated/$username/add/index'
import { Route as AuthenticatedMessagesLayoutConversationsIndexImport } from './routes/_authenticated/messages/_layout/conversations/index'
import { Route as AuthenticatedFriendsLayoutPendingRequestIndexImport } from './routes/_authenticated/friends/_layout/pending-request/index'
import { Route as AuthenticatedFriendsLayoutListIndexImport } from './routes/_authenticated/friends/_layout/list/index'
import { Route as AuthenticatedFriendsLayoutFriendRequestIndexImport } from './routes/_authenticated/friends/_layout/friend-request/index'
import { Route as AuthenticatedFriendsLayoutFindIndexImport } from './routes/_authenticated/friends/_layout/find/index'
import { Route as AuthenticatedUsernameLayoutPostsIndexImport } from './routes/_authenticated/$username/_layout/posts/index'
import { Route as AuthenticatedUsernameLayoutMediaIndexImport } from './routes/_authenticated/$username/_layout/media/index'
import { Route as AuthenticatedMessagesLayoutConversationsLayoutConversationIdIndexImport } from './routes/_authenticated/messages/_layout/conversations/_layout/$conversationId/index'

// Create Virtual Routes

const AuthenticatedMessagesImport = createFileRoute(
  '/_authenticated/messages',
)()
const AuthenticatedFriendsImport = createFileRoute('/_authenticated/friends')()
const AuthenticatedUsernameImport = createFileRoute(
  '/_authenticated/$username',
)()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedMessagesRoute = AuthenticatedMessagesImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedFriendsRoute = AuthenticatedFriendsImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedUsernameRoute = AuthenticatedUsernameImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedMessagesIndexRoute = AuthenticatedMessagesIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any,
)

const AuthenticatedHomeIndexRoute = AuthenticatedHomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedFriendsIndexRoute = AuthenticatedFriendsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedFriendsRoute,
} as any)

const AuthenticatedUsernameIndexRoute = AuthenticatedUsernameIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUsernameRoute,
  } as any,
)

const authVerifyEmailIndexRoute = authVerifyEmailIndexImport.update({
  id: '/(auth)/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => rootRoute,
} as any)

const authResetIndexRoute = authResetIndexImport.update({
  id: '/(auth)/reset/',
  path: '/reset/',
  getParentRoute: () => rootRoute,
} as any)

const authRegisterIndexRoute = authRegisterIndexImport.update({
  id: '/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const authNewPasswordIndexRoute = authNewPasswordIndexImport.update({
  id: '/(auth)/new-password/',
  path: '/new-password/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedMessagesLayoutRoute =
  AuthenticatedMessagesLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)

const AuthenticatedFriendsLayoutRoute = AuthenticatedFriendsLayoutImport.update(
  {
    id: '/_layout',
    getParentRoute: () => AuthenticatedFriendsRoute,
  } as any,
)

const AuthenticatedUsernameLayoutRoute =
  AuthenticatedUsernameLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedUsernameRoute,
  } as any)

const AuthenticatedPostsPostIdIndexRoute =
  AuthenticatedPostsPostIdIndexImport.update({
    id: '/posts/$postId/',
    path: '/posts/$postId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedUsernameEditIndexRoute =
  AuthenticatedUsernameEditIndexImport.update({
    id: '/edit/',
    path: '/edit/',
    getParentRoute: () => AuthenticatedUsernameRoute,
  } as any)

const AuthenticatedUsernameAddIndexRoute =
  AuthenticatedUsernameAddIndexImport.update({
    id: '/add/',
    path: '/add/',
    getParentRoute: () => AuthenticatedUsernameRoute,
  } as any)

const AuthenticatedMessagesLayoutConversationsIndexRoute =
  AuthenticatedMessagesLayoutConversationsIndexImport.update({
    id: '/conversations/',
    path: '/conversations/',
    getParentRoute: () => AuthenticatedMessagesLayoutRoute,
  } as any)

const AuthenticatedFriendsLayoutPendingRequestIndexRoute =
  AuthenticatedFriendsLayoutPendingRequestIndexImport.update({
    id: '/pending-request/',
    path: '/pending-request/',
    getParentRoute: () => AuthenticatedFriendsLayoutRoute,
  } as any)

const AuthenticatedFriendsLayoutListIndexRoute =
  AuthenticatedFriendsLayoutListIndexImport.update({
    id: '/list/',
    path: '/list/',
    getParentRoute: () => AuthenticatedFriendsLayoutRoute,
  } as any)

const AuthenticatedFriendsLayoutFriendRequestIndexRoute =
  AuthenticatedFriendsLayoutFriendRequestIndexImport.update({
    id: '/friend-request/',
    path: '/friend-request/',
    getParentRoute: () => AuthenticatedFriendsLayoutRoute,
  } as any)

const AuthenticatedFriendsLayoutFindIndexRoute =
  AuthenticatedFriendsLayoutFindIndexImport.update({
    id: '/find/',
    path: '/find/',
    getParentRoute: () => AuthenticatedFriendsLayoutRoute,
  } as any)

const AuthenticatedUsernameLayoutPostsIndexRoute =
  AuthenticatedUsernameLayoutPostsIndexImport.update({
    id: '/posts/',
    path: '/posts/',
    getParentRoute: () => AuthenticatedUsernameLayoutRoute,
  } as any)

const AuthenticatedUsernameLayoutMediaIndexRoute =
  AuthenticatedUsernameLayoutMediaIndexImport.update({
    id: '/media/',
    path: '/media/',
    getParentRoute: () => AuthenticatedUsernameLayoutRoute,
  } as any)

const AuthenticatedMessagesLayoutConversationsLayoutConversationIdIndexRoute =
  AuthenticatedMessagesLayoutConversationsLayoutConversationIdIndexImport.update(
    {
      id: '/conversations/_layout/$conversationId/',
      path: '/conversations/$conversationId/',
      getParentRoute: () => AuthenticatedMessagesLayoutRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/$username': {
      id: '/_authenticated/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof AuthenticatedUsernameImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/$username/_layout': {
      id: '/_authenticated/$username/_layout'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof AuthenticatedUsernameLayoutImport
      parentRoute: typeof AuthenticatedUsernameRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/friends/_layout': {
      id: '/_authenticated/friends/_layout'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsLayoutImport
      parentRoute: typeof AuthenticatedFriendsRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/messages/_layout': {
      id: '/_authenticated/messages/_layout'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesLayoutImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/(auth)/new-password/': {
      id: '/(auth)/new-password/'
      path: '/new-password'
      fullPath: '/new-password'
      preLoaderRoute: typeof authNewPasswordIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/reset/': {
      id: '/(auth)/reset/'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof authResetIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/verify-email/': {
      id: '/(auth)/verify-email/'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/$username/': {
      id: '/_authenticated/$username/'
      path: '/'
      fullPath: '/$username/'
      preLoaderRoute: typeof AuthenticatedUsernameIndexImport
      parentRoute: typeof AuthenticatedUsernameImport
    }
    '/_authenticated/friends/': {
      id: '/_authenticated/friends/'
      path: '/'
      fullPath: '/friends/'
      preLoaderRoute: typeof AuthenticatedFriendsIndexImport
      parentRoute: typeof AuthenticatedFriendsImport
    }
    '/_authenticated/home/': {
      id: '/_authenticated/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexImport
      parentRoute: typeof AuthenticatedMessagesImport
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/$username/add/': {
      id: '/_authenticated/$username/add/'
      path: '/add'
      fullPath: '/$username/add'
      preLoaderRoute: typeof AuthenticatedUsernameAddIndexImport
      parentRoute: typeof AuthenticatedUsernameImport
    }
    '/_authenticated/$username/edit/': {
      id: '/_authenticated/$username/edit/'
      path: '/edit'
      fullPath: '/$username/edit'
      preLoaderRoute: typeof AuthenticatedUsernameEditIndexImport
      parentRoute: typeof AuthenticatedUsernameImport
    }
    '/_authenticated/posts/$postId/': {
      id: '/_authenticated/posts/$postId/'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthenticatedPostsPostIdIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/$username/_layout/media/': {
      id: '/_authenticated/$username/_layout/media/'
      path: '/media'
      fullPath: '/$username/media'
      preLoaderRoute: typeof AuthenticatedUsernameLayoutMediaIndexImport
      parentRoute: typeof AuthenticatedUsernameLayoutImport
    }
    '/_authenticated/$username/_layout/posts/': {
      id: '/_authenticated/$username/_layout/posts/'
      path: '/posts'
      fullPath: '/$username/posts'
      preLoaderRoute: typeof AuthenticatedUsernameLayoutPostsIndexImport
      parentRoute: typeof AuthenticatedUsernameLayoutImport
    }
    '/_authenticated/friends/_layout/find/': {
      id: '/_authenticated/friends/_layout/find/'
      path: '/find'
      fullPath: '/friends/find'
      preLoaderRoute: typeof AuthenticatedFriendsLayoutFindIndexImport
      parentRoute: typeof AuthenticatedFriendsLayoutImport
    }
    '/_authenticated/friends/_layout/friend-request/': {
      id: '/_authenticated/friends/_layout/friend-request/'
      path: '/friend-request'
      fullPath: '/friends/friend-request'
      preLoaderRoute: typeof AuthenticatedFriendsLayoutFriendRequestIndexImport
      parentRoute: typeof AuthenticatedFriendsLayoutImport
    }
    '/_authenticated/friends/_layout/list/': {
      id: '/_authenticated/friends/_layout/list/'
      path: '/list'
      fullPath: '/friends/list'
      preLoaderRoute: typeof AuthenticatedFriendsLayoutListIndexImport
      parentRoute: typeof AuthenticatedFriendsLayoutImport
    }
    '/_authenticated/friends/_layout/pending-request/': {
      id: '/_authenticated/friends/_layout/pending-request/'
      path: '/pending-request'
      fullPath: '/friends/pending-request'
      preLoaderRoute: typeof AuthenticatedFriendsLayoutPendingRequestIndexImport
      parentRoute: typeof AuthenticatedFriendsLayoutImport
    }
    '/_authenticated/messages/_layout/conversations/': {
      id: '/_authenticated/messages/_layout/conversations/'
      path: '/conversations'
      fullPath: '/messages/conversations'
      preLoaderRoute: typeof AuthenticatedMessagesLayoutConversationsIndexImport
      parentRoute: typeof AuthenticatedMessagesLayoutImport
    }
    '/_authenticated/messages/_layout/conversations/_layout/$conversationId/': {
      id: '/_authenticated/messages/_layout/conversations/_layout/$conversationId/'
      path: '/conversations/$conversationId'
      fullPath: '/messages/conversations/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesLayoutConversationsLayoutConversationIdIndexImport
      parentRoute: typeof AuthenticatedMessagesLayoutImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedUsernameLayoutRouteChildren {
  AuthenticatedUsernameLayoutMediaIndexRoute: typeof AuthenticatedUsernameLayoutMediaIndexRoute
  AuthenticatedUsernameLayoutPostsIndexRoute: typeof AuthenticatedUsernameLayoutPostsIndexRoute
}

const AuthenticatedUsernameLayoutRouteChildren: AuthenticatedUsernameLayoutRouteChildren =
  {
    AuthenticatedUsernameLayoutMediaIndexRoute:
      AuthenticatedUsernameLayoutMediaIndexRoute,
    AuthenticatedUsernameLayoutPostsIndexRoute:
      AuthenticatedUsernameLayoutPostsIndexRoute,
  }

const AuthenticatedUsernameLayoutRouteWithChildren =
  AuthenticatedUsernameLayoutRoute._addFileChildren(
    AuthenticatedUsernameLayoutRouteChildren,
  )

interface AuthenticatedUsernameRouteChildren {
  AuthenticatedUsernameLayoutRoute: typeof AuthenticatedUsernameLayoutRouteWithChildren
  AuthenticatedUsernameIndexRoute: typeof AuthenticatedUsernameIndexRoute
  AuthenticatedUsernameAddIndexRoute: typeof AuthenticatedUsernameAddIndexRoute
  AuthenticatedUsernameEditIndexRoute: typeof AuthenticatedUsernameEditIndexRoute
}

const AuthenticatedUsernameRouteChildren: AuthenticatedUsernameRouteChildren = {
  AuthenticatedUsernameLayoutRoute:
    AuthenticatedUsernameLayoutRouteWithChildren,
  AuthenticatedUsernameIndexRoute: AuthenticatedUsernameIndexRoute,
  AuthenticatedUsernameAddIndexRoute: AuthenticatedUsernameAddIndexRoute,
  AuthenticatedUsernameEditIndexRoute: AuthenticatedUsernameEditIndexRoute,
}

const AuthenticatedUsernameRouteWithChildren =
  AuthenticatedUsernameRoute._addFileChildren(
    AuthenticatedUsernameRouteChildren,
  )

interface AuthenticatedFriendsLayoutRouteChildren {
  AuthenticatedFriendsLayoutFindIndexRoute: typeof AuthenticatedFriendsLayoutFindIndexRoute
  AuthenticatedFriendsLayoutFriendRequestIndexRoute: typeof AuthenticatedFriendsLayoutFriendRequestIndexRoute
  AuthenticatedFriendsLayoutListIndexRoute: typeof AuthenticatedFriendsLayoutListIndexRoute
  AuthenticatedFriendsLayoutPendingRequestIndexRoute: typeof AuthenticatedFriendsLayoutPendingRequestIndexRoute
}

const AuthenticatedFriendsLayoutRouteChildren: AuthenticatedFriendsLayoutRouteChildren =
  {
    AuthenticatedFriendsLayoutFindIndexRoute:
      AuthenticatedFriendsLayoutFindIndexRoute,
    AuthenticatedFriendsLayoutFriendRequestIndexRoute:
      AuthenticatedFriendsLayoutFriendRequestIndexRoute,
    AuthenticatedFriendsLayoutListIndexRoute:
      AuthenticatedFriendsLayoutListIndexRoute,
    AuthenticatedFriendsLayoutPendingRequestIndexRoute:
      AuthenticatedFriendsLayoutPendingRequestIndexRoute,
  }

const AuthenticatedFriendsLayoutRouteWithChildren =
  AuthenticatedFriendsLayoutRoute._addFileChildren(
    AuthenticatedFriendsLayoutRouteChildren,
  )

interface AuthenticatedFriendsRouteChildren {
  AuthenticatedFriendsLayoutRoute: typeof AuthenticatedFriendsLayoutRouteWithChildren
  AuthenticatedFriendsIndexRoute: typeof AuthenticatedFriendsIndexRoute
}

const AuthenticatedFriendsRouteChildren: AuthenticatedFriendsRouteChildren = {
  AuthenticatedFriendsLayoutRoute: AuthenticatedFriendsLayoutRouteWithChildren,
  AuthenticatedFriendsIndexRoute: AuthenticatedFriendsIndexRoute,
}

const AuthenticatedFriendsRouteWithChildren =
  AuthenticatedFriendsRoute._addFileChildren(AuthenticatedFriendsRouteChildren)

interface AuthenticatedMessagesLayoutRouteChildren {
  AuthenticatedMessagesLayoutConversationsIndexRoute: typeof AuthenticatedMessagesLayoutConversationsIndexRoute
  AuthenticatedMessagesLayoutConversationsLayoutConversationIdIndexRoute: typeof AuthenticatedMessagesLayoutConversationsLayoutConversationIdIndexRoute
}

const AuthenticatedMessagesLayoutRouteChildren: AuthenticatedMessagesLayoutRouteChildren =
  {
    AuthenticatedMessagesLayoutConversationsIndexRoute:
      AuthenticatedMessagesLayoutConversationsIndexRoute,
    AuthenticatedMessagesLayoutConversationsLayoutConversationIdIndexRoute:
      AuthenticatedMessagesLayoutConversationsLayoutConversationIdIndexRoute,
  }

const AuthenticatedMessagesLayoutRouteWithChildren =
  AuthenticatedMessagesLayoutRoute._addFileChildren(
    AuthenticatedMessagesLayoutRouteChildren,
  )

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesLayoutRoute: typeof AuthenticatedMessagesLayoutRouteWithChildren
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesLayoutRoute:
    AuthenticatedMessagesLayoutRouteWithChildren,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedUsernameRoute: typeof AuthenticatedUsernameRouteWithChildren
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRouteWithChildren
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedHomeIndexRoute: typeof AuthenticatedHomeIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedPostsPostIdIndexRoute: typeof AuthenticatedPostsPostIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedUsernameRoute: AuthenticatedUsernameRouteWithChildren,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRouteWithChildren,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedHomeIndexRoute: AuthenticatedHomeIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedPostsPostIdIndexRoute: AuthenticatedPostsPostIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/$username': typeof AuthenticatedUsernameLayoutRouteWithChildren
  '/friends': typeof AuthenticatedFriendsLayoutRouteWithChildren
  '/messages': typeof AuthenticatedMessagesLayoutRouteWithChildren
  '/new-password': typeof authNewPasswordIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/reset': typeof authResetIndexRoute
  '/verify-email': typeof authVerifyEmailIndexRoute
  '/$username/': typeof AuthenticatedUsernameIndexRoute
  '/friends/': typeof AuthenticatedFriendsIndexRoute
  '/home': typeof AuthenticatedHomeIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/$username/add': typeof AuthenticatedUsernameAddIndexRoute
  '/$username/edit': typeof AuthenticatedUsernameEditIndexRoute
  '/posts/$postId': typeof AuthenticatedPostsPostIdIndexRoute
  '/$username/media': typeof AuthenticatedUsernameLayoutMediaIndexRoute
  '/$username/posts': typeof AuthenticatedUsernameLayoutPostsIndexRoute
  '/friends/find': typeof AuthenticatedFriendsLayoutFindIndexRoute
  '/friends/friend-request': typeof AuthenticatedFriendsLayoutFriendRequestIndexRoute
  '/friends/list': typeof AuthenticatedFriendsLayoutListIndexRoute
  '/friends/pending-request': typeof AuthenticatedFriendsLayoutPendingRequestIndexRoute
  '/messages/conversations': typeof AuthenticatedMessagesLayoutConversationsIndexRoute
  '/messages/conversations/$conversationId': typeof AuthenticatedMessagesLayoutConversationsLayoutConversationIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/$username': typeof AuthenticatedUsernameIndexRoute
  '/friends': typeof AuthenticatedFriendsIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/new-password': typeof authNewPasswordIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/reset': typeof authResetIndexRoute
  '/verify-email': typeof authVerifyEmailIndexRoute
  '/home': typeof AuthenticatedHomeIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/$username/add': typeof AuthenticatedUsernameAddIndexRoute
  '/$username/edit': typeof AuthenticatedUsernameEditIndexRoute
  '/posts/$postId': typeof AuthenticatedPostsPostIdIndexRoute
  '/$username/media': typeof AuthenticatedUsernameLayoutMediaIndexRoute
  '/$username/posts': typeof AuthenticatedUsernameLayoutPostsIndexRoute
  '/friends/find': typeof AuthenticatedFriendsLayoutFindIndexRoute
  '/friends/friend-request': typeof AuthenticatedFriendsLayoutFriendRequestIndexRoute
  '/friends/list': typeof AuthenticatedFriendsLayoutListIndexRoute
  '/friends/pending-request': typeof AuthenticatedFriendsLayoutPendingRequestIndexRoute
  '/messages/conversations': typeof AuthenticatedMessagesLayoutConversationsIndexRoute
  '/messages/conversations/$conversationId': typeof AuthenticatedMessagesLayoutConversationsLayoutConversationIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/$username': typeof AuthenticatedUsernameRouteWithChildren
  '/_authenticated/$username/_layout': typeof AuthenticatedUsernameLayoutRouteWithChildren
  '/_authenticated/friends': typeof AuthenticatedFriendsRouteWithChildren
  '/_authenticated/friends/_layout': typeof AuthenticatedFriendsLayoutRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/messages/_layout': typeof AuthenticatedMessagesLayoutRouteWithChildren
  '/(auth)/new-password/': typeof authNewPasswordIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/(auth)/reset/': typeof authResetIndexRoute
  '/(auth)/verify-email/': typeof authVerifyEmailIndexRoute
  '/_authenticated/$username/': typeof AuthenticatedUsernameIndexRoute
  '/_authenticated/friends/': typeof AuthenticatedFriendsIndexRoute
  '/_authenticated/home/': typeof AuthenticatedHomeIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/$username/add/': typeof AuthenticatedUsernameAddIndexRoute
  '/_authenticated/$username/edit/': typeof AuthenticatedUsernameEditIndexRoute
  '/_authenticated/posts/$postId/': typeof AuthenticatedPostsPostIdIndexRoute
  '/_authenticated/$username/_layout/media/': typeof AuthenticatedUsernameLayoutMediaIndexRoute
  '/_authenticated/$username/_layout/posts/': typeof AuthenticatedUsernameLayoutPostsIndexRoute
  '/_authenticated/friends/_layout/find/': typeof AuthenticatedFriendsLayoutFindIndexRoute
  '/_authenticated/friends/_layout/friend-request/': typeof AuthenticatedFriendsLayoutFriendRequestIndexRoute
  '/_authenticated/friends/_layout/list/': typeof AuthenticatedFriendsLayoutListIndexRoute
  '/_authenticated/friends/_layout/pending-request/': typeof AuthenticatedFriendsLayoutPendingRequestIndexRoute
  '/_authenticated/messages/_layout/conversations/': typeof AuthenticatedMessagesLayoutConversationsIndexRoute
  '/_authenticated/messages/_layout/conversations/_layout/$conversationId/': typeof AuthenticatedMessagesLayoutConversationsLayoutConversationIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/$username'
    | '/friends'
    | '/messages'
    | '/new-password'
    | '/register'
    | '/reset'
    | '/verify-email'
    | '/$username/'
    | '/friends/'
    | '/home'
    | '/messages/'
    | '/notifications'
    | '/$username/add'
    | '/$username/edit'
    | '/posts/$postId'
    | '/$username/media'
    | '/$username/posts'
    | '/friends/find'
    | '/friends/friend-request'
    | '/friends/list'
    | '/friends/pending-request'
    | '/messages/conversations'
    | '/messages/conversations/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/$username'
    | '/friends'
    | '/messages'
    | '/new-password'
    | '/register'
    | '/reset'
    | '/verify-email'
    | '/home'
    | '/notifications'
    | '/$username/add'
    | '/$username/edit'
    | '/posts/$postId'
    | '/$username/media'
    | '/$username/posts'
    | '/friends/find'
    | '/friends/friend-request'
    | '/friends/list'
    | '/friends/pending-request'
    | '/messages/conversations'
    | '/messages/conversations/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/$username'
    | '/_authenticated/$username/_layout'
    | '/_authenticated/friends'
    | '/_authenticated/friends/_layout'
    | '/_authenticated/messages'
    | '/_authenticated/messages/_layout'
    | '/(auth)/new-password/'
    | '/(auth)/register/'
    | '/(auth)/reset/'
    | '/(auth)/verify-email/'
    | '/_authenticated/$username/'
    | '/_authenticated/friends/'
    | '/_authenticated/home/'
    | '/_authenticated/messages/'
    | '/_authenticated/notifications/'
    | '/_authenticated/$username/add/'
    | '/_authenticated/$username/edit/'
    | '/_authenticated/posts/$postId/'
    | '/_authenticated/$username/_layout/media/'
    | '/_authenticated/$username/_layout/posts/'
    | '/_authenticated/friends/_layout/find/'
    | '/_authenticated/friends/_layout/friend-request/'
    | '/_authenticated/friends/_layout/list/'
    | '/_authenticated/friends/_layout/pending-request/'
    | '/_authenticated/messages/_layout/conversations/'
    | '/_authenticated/messages/_layout/conversations/_layout/$conversationId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  authNewPasswordIndexRoute: typeof authNewPasswordIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
  authResetIndexRoute: typeof authResetIndexRoute
  authVerifyEmailIndexRoute: typeof authVerifyEmailIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  authNewPasswordIndexRoute: authNewPasswordIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
  authResetIndexRoute: authResetIndexRoute,
  authVerifyEmailIndexRoute: authVerifyEmailIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/login",
        "/(auth)/new-password/",
        "/(auth)/register/",
        "/(auth)/reset/",
        "/(auth)/verify-email/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/$username",
        "/_authenticated/friends",
        "/_authenticated/messages",
        "/_authenticated/home/",
        "/_authenticated/notifications/",
        "/_authenticated/posts/$postId/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/$username": {
      "filePath": "_authenticated/$username",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/$username/_layout",
        "/_authenticated/$username/",
        "/_authenticated/$username/add/",
        "/_authenticated/$username/edit/"
      ]
    },
    "/_authenticated/$username/_layout": {
      "filePath": "_authenticated/$username/_layout.tsx",
      "parent": "/_authenticated/$username",
      "children": [
        "/_authenticated/$username/_layout/media/",
        "/_authenticated/$username/_layout/posts/"
      ]
    },
    "/_authenticated/friends": {
      "filePath": "_authenticated/friends",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/friends/_layout",
        "/_authenticated/friends/"
      ]
    },
    "/_authenticated/friends/_layout": {
      "filePath": "_authenticated/friends/_layout.tsx",
      "parent": "/_authenticated/friends",
      "children": [
        "/_authenticated/friends/_layout/find/",
        "/_authenticated/friends/_layout/friend-request/",
        "/_authenticated/friends/_layout/list/",
        "/_authenticated/friends/_layout/pending-request/"
      ]
    },
    "/_authenticated/messages": {
      "filePath": "_authenticated/messages",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/messages/_layout",
        "/_authenticated/messages/"
      ]
    },
    "/_authenticated/messages/_layout": {
      "filePath": "_authenticated/messages/_layout.tsx",
      "parent": "/_authenticated/messages",
      "children": [
        "/_authenticated/messages/_layout/conversations/",
        "/_authenticated/messages/_layout/conversations/_layout/$conversationId/"
      ]
    },
    "/(auth)/new-password/": {
      "filePath": "(auth)/new-password/index.tsx"
    },
    "/(auth)/register/": {
      "filePath": "(auth)/register/index.tsx"
    },
    "/(auth)/reset/": {
      "filePath": "(auth)/reset/index.tsx"
    },
    "/(auth)/verify-email/": {
      "filePath": "(auth)/verify-email/index.tsx"
    },
    "/_authenticated/$username/": {
      "filePath": "_authenticated/$username/index.tsx",
      "parent": "/_authenticated/$username"
    },
    "/_authenticated/friends/": {
      "filePath": "_authenticated/friends/index.tsx",
      "parent": "/_authenticated/friends"
    },
    "/_authenticated/home/": {
      "filePath": "_authenticated/home/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/messages/": {
      "filePath": "_authenticated/messages/index.tsx",
      "parent": "/_authenticated/messages"
    },
    "/_authenticated/notifications/": {
      "filePath": "_authenticated/notifications/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/$username/add/": {
      "filePath": "_authenticated/$username/add/index.tsx",
      "parent": "/_authenticated/$username"
    },
    "/_authenticated/$username/edit/": {
      "filePath": "_authenticated/$username/edit/index.tsx",
      "parent": "/_authenticated/$username"
    },
    "/_authenticated/posts/$postId/": {
      "filePath": "_authenticated/posts/$postId/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/$username/_layout/media/": {
      "filePath": "_authenticated/$username/_layout/media/index.tsx",
      "parent": "/_authenticated/$username/_layout"
    },
    "/_authenticated/$username/_layout/posts/": {
      "filePath": "_authenticated/$username/_layout/posts/index.tsx",
      "parent": "/_authenticated/$username/_layout"
    },
    "/_authenticated/friends/_layout/find/": {
      "filePath": "_authenticated/friends/_layout/find/index.tsx",
      "parent": "/_authenticated/friends/_layout"
    },
    "/_authenticated/friends/_layout/friend-request/": {
      "filePath": "_authenticated/friends/_layout/friend-request/index.tsx",
      "parent": "/_authenticated/friends/_layout"
    },
    "/_authenticated/friends/_layout/list/": {
      "filePath": "_authenticated/friends/_layout/list/index.tsx",
      "parent": "/_authenticated/friends/_layout"
    },
    "/_authenticated/friends/_layout/pending-request/": {
      "filePath": "_authenticated/friends/_layout/pending-request/index.tsx",
      "parent": "/_authenticated/friends/_layout"
    },
    "/_authenticated/messages/_layout/conversations/": {
      "filePath": "_authenticated/messages/_layout/conversations/index.tsx",
      "parent": "/_authenticated/messages/_layout"
    },
    "/_authenticated/messages/_layout/conversations/_layout/$conversationId/": {
      "filePath": "_authenticated/messages/_layout/conversations/_layout/$conversationId/index.tsx",
      "parent": "/_authenticated/messages/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
