version: "3.9"
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend.dev
    image: frontend-dev:latest
    container_name: frontend-dev
    volumes:
      - ../frontend:/app
      - ../frontend:/app/node_modules
    ports:
      - "3001:3000"
    env_file:
      - ../.env
    environment:
      - VITE_SERVER_URL
      - APP_ORIGIN
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend.dev
    image: backend-dev:latest
    container_name: backend-dev
    volumes:
      - ../backend:/app
    ports:
      - "5001:5000"
    env_file:
      - ../.env
    environment:
      - VITE_SERVER_URL
      - DATABASE_URL
      - APP_ORIGIN
      - BASE_PATH
      - NODE_ENV
      - PORT
      - ACCESS_TOKEN_SECRET
      - REFRESH_TOKEN_SECRET
      - RESEND_API_KEY
      - RESEND_VERIFIED_DOMAIN
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_BUCKET_NAME
    command: ["npm", "run", "dev"]

  # You can add a database here if you need it in dev
  # For example Postgres:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data

volumes:
  db_data_dev:
