FROM node:20
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Again, source code will be mounted as a volume
EXPOSE 5000
CMD ["npm", "run", "dev"] 
# Assuming you have a "dev" script in package.json that runs nodemon or similar
