name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and push Client Docker image
      - name: Build and push Client
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/onlyfriends-client:latest ./client
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/onlyfriends-client:latest

      # Build and push Server Docker image
      - name: Build and push Server
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/onlyfriends-server:latest ./server
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/onlyfriends-server:latest

      # Build and push Nginx Docker image
      - name: Build and push Nginx
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/onlyfriends-nginx:latest ./nginx
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/onlyfriends-nginx:latest

      # Deploy to EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "."
          target: ${{ secrets.REMOTE_PATH }}

      - name: SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ${{ secrets.REMOTE_PATH }}
            docker-compose pull
            docker-compose up -d --build
