name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 4. Build and push Client Docker image
      - name: Build and push Client
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/onlyfriends-client:latest ./client
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/onlyfriends-client:latest

      # 5. Build and push Server Docker image
      - name: Build and push Server
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/onlyfriends-server:latest ./server
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/onlyfriends-server:latest

      # 6. Build and push Nginx Docker image
      - name: Build and push Nginx
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/onlyfriends-nginx:latest ./nginx
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/onlyfriends-nginx:latest

      # 7. Deploy to EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e

            # Navigate to the deployment directory
            cd ${{ secrets.REMOTE_PATH }}

            # Create/update the .env file with necessary environment variables
            cat <<EOF > .env
            NODE_ENV=${{ secrets.NODE_ENV }}
            VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }}
            VITE_ALLOWED_IMAGE_DOMAIN=${{ secrets.VITE_ALLOWED_IMAGE_DOMAIN }}
            PORT=${{ secrets.PORT }}
            APP_ORIGIN=${{ secrets.APP_ORIGIN }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}
            REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            RESEND_VERIFIED_DOMAIN=${{ secrets.RESEND_VERIFIED_DOMAIN }}
            ALLOWED_IMAGE_DOMAIN=${{ secrets.ALLOWED_IMAGE_DOMAIN }}
            AWS_REGION=${{ secrets.AWS_REGION }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
            EOF

            # Pull the latest Docker images
            docker-compose pull

            # Rebuild and restart the containers
            docker-compose up -d --build
